### ISSUE TITLE
Shift+Click Shortcut

### ISSUE THREAD

**Issue by uwap** [uwap/space-map#9]
When an icon is pressed with shift and left click it should do the primary (first) action. For example shift + left clicking the onkyo should toggle its power.

**Comment by Ranlvor** [comment]
Fickja! \o/

Bleibt die Frage, wie man dieses Konzept neuen Usern vermitteln kann. Doku ließt vermutlich niemand und es wäre schade, wenn dieses Feature nicht genutzt wird weil die Nutzer es einfach nicht kennen.

**Comment by steeph-k** [comment]
Ich würde es zur Legende packen,falls es auf der Ansicht so eine gibt.

**Comment by Bfritz0815** [comment]
Oder im title Tag erwähnen

Am 04.11.2017 10:20 schrieb "Ranlvor" <notifications@github.com>:
